# Generated by Django 4.0.3 on 2022-04-27 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('dept_place', models.CharField(max_length=100)),
                ('dest_place', models.CharField(max_length=100)),
                ('dep_time', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('fare', models.CharField(max_length=100)),
                ('seat_map', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('dep_place', models.CharField(max_length=100)),
                ('dest_place', models.CharField(max_length=100)),
                ('dep_time', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('flight_class', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('seat_map', models.ImageField(null=True, upload_to='images/')),
                ('fare', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('night', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('inclusions', models.CharField(max_length=100)),
                ('exclusions', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dep_place', models.CharField(max_length=100)),
                ('dest_place', models.CharField(max_length=100)),
                ('dep_time', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('ac_fare', models.CharField(max_length=100)),
                ('sleeper_fare', models.CharField(max_length=100)),
                ('first_fare', models.CharField(max_length=100)),
                ('second_fare', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=100)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=100)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.employee'),
        ),
    ]
