# Generated by Django 4.0.3 on 2022-04-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_package_food_package_guides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='feedback',
            new_name='complaint',
        ),
    ]
